files:
  - source: /docs/zh/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /docs/zh/features/*.md
    translation: /docs/%two_letters_code%/features/%original_file_name%
  - source: /docs/zh/statements/*.md
    translation: /docs/%two_letters_code%/statements/%original_file_name%
  - source: /docs/zh/advanced/*.md
    translation: /docs/%two_letters_code%/advanced/%original_file_name%
