files:
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /docs/features/*.md
    translation: /docs/%two_letters_code%/features/%original_file_name%
  - source: /docs/statements/*.md
    translation: /docs/%two_letters_code%/statements/%original_file_name%
  - source: /docs/advanced/*.md
    translation: /docs/%two_letters_code%/advanced/%original_file_name%
